TencentBlueKing/blueking-apigateway-operator

controllers/bkgatewayconfig_controller.go, pkg/apisix/synchronizer/file/store.go
* fix: update for micro gateway (#6)
=> fix: update for micro gateway (#6)

Makefile, cmd/root.go, cmd/version.go, internal/tracer/tracer.go, pkg/version/version.go
=> feat: add version subcommand

.golangci.yaml, controllers/bkgatewaypluginmetadata_controller.go, controllers/bkgatewayresource_controller.go, controllers/bkgatewayservice_controller.go, controllers/bkgatewaystage_controller.go, controllers/bkgatewaytls_controller.go, controllers/secret_controller.go, controllers/utils.go, pkg/agent/agent.go, pkg/discovery-operator-frame/frame.go, pkg/discovery-operator-frame/types/registry.go, pkg/radixtree/radix.go, pkg/registry/etcdadapter.go
=> style: add some linter and fix lint

pkg/leaderelection/etcdadapter.go, pkg/leaderelection/kubeadapter.go
=> feat: fix  elector leader log

pkg/apisix/synchronizer/etcd/store.go
=> bugfix: etcd resource alter metric

config.yaml.tpl, pkg/apisix/synchronizer/etcd/store.go, pkg/config/config.go, pkg/runner/common.go
fix etcd put data inconsistencies
=> fix: fix etcd put

pkg/client/apisix.go
=> fix: fix get version fail bug

pkg/client/apisix.go
* fix: fix get version fail bug
=> backport: fix get version fail bug (#28)

pkg/client/apisix.go, pkg/config/config.go
=> fix: fix publish version route

pkg/client/apisix.go, pkg/config/config.go
=> Feat publish verison route

pkg/client/apisix.go, pkg/utils/ip.go
=> fix: fix apisix client request header

pkg/agent/agent.go, pkg/client/core_api_slz.go, pkg/constant/event.go, pkg/eventreporter/reporter.go
=> fix: fix start sync publish event report

pkg/agent/agent.go
=> bugfix: sync all stage

pkg/agent/agent.go
=> backport: bugfix sync all stage (#40)

pkg/client/apisix.go, pkg/client/base.go, pkg/eventreporter/reporter.go, pkg/registry/etcdadapter.go, pkg/registry/etcdadapter_test.go
=> fix: fix publish stage duplicate bug

pkg/agent/timer/timer.go, pkg/constant/event.go, pkg/eventreporter/reporter.go
Fixes publish stage duplicate bug
=> Fix publish stage deuplicate (#46)

config.yaml.tpl, pkg/apisix/synchronizer/etcd/diff.go, pkg/apisix/synchronizer/etcd/diff_test.go, pkg/apisix/synchronizer/init.go, pkg/apisix/synchronizer/synchronizer.go, pkg/apisix/synchronizer/virtual_stage.go, pkg/apisix/synchronizer/virtual_stage_test.go, pkg/config/config.go
=> Fix publish diff invalid

pkg/apisix/synchronizer/etcd/diff.go, pkg/apisix/synchronizer/etcd/diff_test.go, pkg/apisix/synchronizer/etcd/store.go, pkg/apisix/synchronizer/metric.go, pkg/metric/metric_def.go
add diff metircs and add some log
=> feat: add diff metircs and add some log

Makefile, cmd/init.go, config.yaml.tpl, pkg/apisix/synchronizer/etcd/store.go, pkg/leaderelection/etcdadapter.go, pkg/leaderelection/kubeadapter.go, pkg/leaderelection/metric.go, pkg/logging/init.go, pkg/metric/metric_def.go
add panic sentry and leader election metric
=> feat: add panic sentry and leader election metric

Makefile, cmd/init.go, config.yaml.tpl, pkg/apisix/synchronizer/etcd/store.go, pkg/leaderelection/etcdadapter.go, pkg/leaderelection/kubeadapter.go, pkg/leaderelection/metric.go, pkg/logging/init.go, pkg/metric/metric_def.go
=> feat: add panic sentry and leader election metric (#58)

pkg/agent/agent.go, pkg/apisix/synchronizer/etcd/resource.go, pkg/commiter/commiter.go, pkg/config/config.go, pkg/eventreporter/reporter.go, pkg/registry/etcdadapter.go, pkg/server/server.go, tests/integration/operator_test.go
- 修复watch client 协程泄露
- 修复event 上报网关下线情况导致panic问题
- pprof 路由添加认证
=> fix: fix watch bug and event report bug

pkg/client/apisix.go
修复上报当版本路由找不到时，response body没有关闭导致的协程泄露
=> fix: fix goroutine leak

pkg/eventreporter/reporter.go, tests/integration/operator_test.go
=> fix: fix delete gateway panic and add delete gateway publish intergration test

pkg/client/apisix.go, tests/integration/operator_test.go
disable version probe keepalive
=> feat: disable version probe keepalive

pkg/apisix/synchronizer/etcd/store.go, pkg/config/config.go
- fix kube leader election config
- opt diff log
=> fix kube leader election config (1.12)

pkg/commiter/conversion/resource.go
=> fix: upsteam convert retries

go.mod, go.sum, pkg/registry/kubeadapter.go, pkg/utils/uuid.go
=> update: remove github.com/satori/go.uuid

pkg/client/core_api_slz.go, pkg/eventreporter/reporter.go
=> fix(event): add event ts

pkg/agent/agent.go, pkg/agent/timer/timer.go, pkg/api/router.go, pkg/apisix/synchronizer/etcd/diff.go, pkg/apisix/synchronizer/etcd/store.go, pkg/apisix/synchronizer/synchronizer.go, pkg/apisix/types.go, pkg/client/apisix.go, pkg/client/apisix_slz.go, pkg/client/core_api.go, pkg/client/resource.go, pkg/commiter/cert/cert.go, pkg/commiter/commiter.go, pkg/config/config.go, pkg/discovery-operator-frame/frame.go, pkg/discovery-operator-frame/options/options.go, pkg/discovery-operator-frame/service/service.go, pkg/eventreporter/reporter.go, pkg/leaderelection/kubeadapter.go, pkg/leaderelection/metric.go, pkg/registry/etcdadapter.go, pkg/runner/kube.go, pkg/server/server.go, pkg/utils/response.go, pkg/utils/validation.go, pkg/version/version.go, tests/integration/util.go
=> style: fix lints

docs/debug/README.md, docs/debug/README_EN.md
=> fix(docs/debug): 文档补充

docs/debug/README.md, docs/debug/README_EN.md
=> fix(docs/debug): 文档补充 (#92)

config.yaml.tpl, pkg/apisix/synchronizer/etcd/store.go, pkg/apisix/synchronizer/synchronizer_test.go, pkg/biz/apigw.go, pkg/config/config.go, pkg/runner/common.go
fix: fix del load config(暂时在删除的时候延迟一下删除service，保证没有watch到变更的关联的route不会报错)
=> fix: fix del load config

pkg/apisix/synchronizer/etcd/store.go, pkg/commiter/commiter.go, pkg/commiter/commiter_test.go, pkg/config/config.go
=> fix(commiter): fix stage commit

pkg/commiter/commiter.go
=> fix(commiter): fix operator publish (#98)
